// ================================
// FILE: src/lib/mockNearby.js
// ================================
// 10 usuarios fijos (fotos realistas) + datos completos
export const MOCK_USERS = [
  {
    id: 'mock_u1',
    name: 'Sofía',
    photo: 'https://randomuser.me/api/portraits/women/68.jpg',
    vehicle_type: 'car',
    brand: 'SEAT',
    model: 'León',
    color: 'blanco',
    plate: '1234 JKL',
    phone: '+34 612 345 901',
  },
  {
    id: 'mock_u2',
    name: 'Hugo',
    photo: 'https://randomuser.me/api/portraits/men/32.jpg',
    vehicle_type: 'suv',
    brand: 'Nissan',
    model: 'Qashqai',
    color: 'gris',
    plate: '5678 MNP',
    phone: '+34 611 224 872',
  },
  {
    id: 'mock_u3',
    name: 'Nuria',
    photo: 'https://randomuser.me/api/portraits/women/44.jpg',
    vehicle_type: 'van',
    brand: 'Volkswagen',
    model: 'Transporter',
    color: 'negro',
    plate: '9012 BCD',
    phone: '+34 613 908 771',
  },
  {
    id: 'mock_u4',
    name: 'Iván',
    photo: 'https://randomuser.me/api/portraits/men/75.jpg',
    vehicle_type: 'car',
    brand: 'Renault',
    model: 'Clio',
    color: 'rojo',
    plate: '3456 FGH',
    phone: '+34 610 552 330',
  },
  {
    id: 'mock_u5',
    name: 'Marco',
    photo: 'https://randomuser.me/api/portraits/men/12.jpg',
    vehicle_type: 'car',
    brand: 'Peugeot',
    model: '208',
    color: 'azul',
    plate: '7890 QRS',
    phone: '+34 614 401 992',
  },
  {
    id: 'mock_u6',
    name: 'Laura',
    photo: 'https://randomuser.me/api/portraits/women/12.jpg',
    vehicle_type: 'suv',
    brand: 'Kia',
    model: 'Sportage',
    color: 'verde',
    plate: '2468 TUV',
    phone: '+34 615 993 120',
  },
  {
    id: 'mock_u7',
    name: 'Dani',
    photo: 'https://randomuser.me/api/portraits/men/46.jpg',
    vehicle_type: 'car',
    brand: 'Toyota',
    model: 'Corolla',
    color: 'negro',
    plate: '1357 WXY',
    phone: '+34 616 220 415',
  },
  {
    id: 'mock_u8',
    name: 'Paula',
    photo: 'https://randomuser.me/api/portraits/women/25.jpg',
    vehicle_type: 'van',
    brand: 'Mercedes',
    model: 'Vito',
    color: 'gris',
    plate: '8642 ZAB',
    phone: '+34 617 882 064',
  },
  {
    id: 'mock_u9',
    name: 'Álvaro',
    photo: 'https://randomuser.me/api/portraits/men/19.jpg',
    vehicle_type: 'car',
    brand: 'Volkswagen',
    model: 'Golf',
    color: 'blanco',
    plate: '9753 CDE',
    phone: '+34 618 771 203',
  },
  {
    id: 'mock_u10',
    name: 'Claudia',
    photo: 'https://randomuser.me/api/portraits/women/55.jpg',
    vehicle_type: 'suv',
    brand: 'Hyundai',
    model: 'Tucson',
    color: 'morado',
    plate: '1122 FJK',
    phone: '+34 619 330 778',
  },
];
