// Mock data con 10 usuarios y ejemplos de todas las funcionalidades
export const mockUsers = [
  {
    id: 'user1',
    name: 'Sofia García',
    email: 'sofia@example.com',
    photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop',
    car_brand: 'Audi',
    car_model: 'A3',
    car_color: 'blanco',
    car_plate: '3456 JKL',
    vehicle_type: 'car',
    credits: 45.50,
    allow_phone_calls: true,
    phone: '+34 615 123 456'
  },
  {
    id: 'user2',
    name: 'Carlos Martínez',
    email: 'carlos@example.com',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop',
    car_brand: 'BMW',
    car_model: '320i',
    car_color: 'negro',
    car_plate: '7890 ABC',
    vehicle_type: 'car',
    credits: 89.20,
    allow_phone_calls: true,
    phone: '+34 622 456 789'
  },
  {
    id: 'user3',
    name: 'María López',
    email: 'maria@example.com',
    photo: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop',
    car_brand: 'Mercedes',
    car_model: 'C200',
    car_color: 'gris',
    car_plate: '1234 MBZ',
    vehicle_type: 'car',
    credits: 120.00,
    allow_phone_calls: true,
    phone: '+34 678 234 567'
  },
  {
    id: 'user4',
    name: 'Juan Rodríguez',
    email: 'juan@example.com',
    photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop',
    car_brand: 'Volkswagen',
    car_model: 'Golf',
    car_color: 'azul',
    car_plate: '5678 VW',
    vehicle_type: 'car',
    credits: 65.75,
    allow_phone_calls: false,
    phone: ''
  },
  {
    id: 'user5',
    name: 'Laura Sánchez',
    email: 'laura@example.com',
    photo: 'https://images.unsplash.com/photo-1516228714891-0f16fcad4991?w=200&h=200&fit=crop',
    car_brand: 'Toyota',
    car_model: 'Corolla',
    car_color: 'rojo',
    car_plate: '9012 TYT',
    vehicle_type: 'car',
    credits: 55.30,
    allow_phone_calls: true,
    phone: '+34 691 567 234'
  },
  {
    id: 'user6',
    name: 'Pedro Fernández',
    email: 'pedro@example.com',
    photo: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&h=200&fit=crop',
    car_brand: 'Renault',
    car_model: 'Megane',
    car_color: 'blanco',
    car_plate: '3456 RNL',
    vehicle_type: 'car',
    credits: 78.60,
    allow_phone_calls: true,
    phone: '+34 645 789 123'
  },
  {
    id: 'user7',
    name: 'Andrea Gimenez',
    email: 'andrea@example.com',
    photo: 'https://images.unsplash.com/photo-1516534775068-bb57846d991c?w=200&h=200&fit=crop',
    car_brand: 'Seat',
    car_model: 'Ibiza',
    car_color: 'amarillo',
    car_plate: '7890 SEAT',
    vehicle_type: 'car',
    credits: 92.15,
    allow_phone_calls: true,
    phone: '+34 658 901 234'
  },
  {
    id: 'user8',
    name: 'Miguel Ángel López',
    email: 'miguel@example.com',
    photo: 'https://images.unsplash.com/photo-1507009596925-ceb15e1908d5?w=200&h=200&fit=crop',
    car_brand: 'Peugeot',
    car_model: '308',
    car_color: 'gris',
    car_plate: '2468 PEU',
    vehicle_type: 'suv',
    credits: 110.45,
    allow_phone_calls: true,
    phone: '+34 672 345 678'
  },
  {
    id: 'user9',
    name: 'Beatriz Moreno',
    email: 'beatriz@example.com',
    photo: 'https://images.unsplash.com/photo-1514895245098-b8c0a2ce7e12?w=200&h=200&fit=crop',
    car_brand: 'Fiat',
    car_model: '500',
    car_color: 'azul',
    car_plate: '1357 FIA',
    vehicle_type: 'car',
    credits: 38.20,
    allow_phone_calls: true,
    phone: '+34 699 456 789'
  },
  {
    id: 'user10',
    name: 'David Español',
    email: 'david@example.com',
    photo: 'https://images.unsplash.com/photo-1512070679279-338ba220e826?w=200&h=200&fit=crop',
    car_brand: 'Honda',
    car_model: 'Civic',
    car_color: 'negro',
    car_plate: '2468 HON',
    vehicle_type: 'car',
    credits: 156.80,
    allow_phone_calls: true,
    phone: '+34 687 123 456'
  }
];

export const mockAlerts = [
  {
    id: 'alert1',
    user_id: 'user1',
    user_name: 'Sofia',
    user_photo: mockUsers[0].photo,
    car_brand: 'Audi',
    car_model: 'A3',
    car_color: 'blanco',
    car_plate: '3456 JKL',
    vehicle_type: 'car',
    address: 'Calle de Alcalá, 45, Madrid',
    available_in_minutes: 12,
    price: 3.50,
    latitude: 40.4168,
    longitude: -3.7038,
    allow_phone_calls: true,
    status: 'active',
    created_date: new Date(Date.now() - 5 * 60000).toISOString()
  },
  {
    id: 'alert2',
    user_id: 'user2',
    user_name: 'Carlos',
    user_photo: mockUsers[1].photo,
    car_brand: 'BMW',
    car_model: '320i',
    car_color: 'negro',
    car_plate: '7890 ABC',
    vehicle_type: 'car',
    address: 'Paseo de la Castellana, 200, Madrid',
    available_in_minutes: 25,
    price: 4.00,
    latitude: 40.4605,
    longitude: -3.6883,
    allow_phone_calls: true,
    status: 'active',
    created_date: new Date(Date.now() - 15 * 60000).toISOString()
  },
  {
    id: 'alert3',
    user_id: 'user3',
    user_name: 'María',
    user_photo: mockUsers[2].photo,
    car_brand: 'Mercedes',
    car_model: 'C200',
    car_color: 'gris',
    car_plate: '1234 MBZ',
    vehicle_type: 'car',
    address: 'Gran Vía, 28, Madrid',
    available_in_minutes: 18,
    price: 5.00,
    latitude: 40.4182,
    longitude: -3.7090,
    allow_phone_calls: true,
    status: 'active',
    created_date: new Date(Date.now() - 8 * 60000).toISOString()
  },
  {
    id: 'alert4',
    user_id: 'user4',
    user_name: 'Juan',
    user_photo: mockUsers[3].photo,
    car_brand: 'Volkswagen',
    car_model: 'Golf',
    car_color: 'azul',
    car_plate: '5678 VW',
    vehicle_type: 'car',
    address: 'Plaza Mayor, 1, Madrid',
    available_in_minutes: 35,
    price: 2.50,
    latitude: 40.4155,
    longitude: -3.7075,
    allow_phone_calls: false,
    status: 'active',
    created_date: new Date(Date.now() - 20 * 60000).toISOString()
  },
  {
    id: 'alert5',
    user_id: 'user5',
    user_name: 'Laura',
    user_photo: mockUsers[4].photo,
    car_brand: 'Toyota',
    car_model: 'Corolla',
    car_color: 'rojo',
    car_plate: '9012 TYT',
    vehicle_type: 'car',
    address: 'Calle Ortega y Gasset, 10, Madrid',
    available_in_minutes: 22,
    price: 3.00,
    latitude: 40.4270,
    longitude: -3.6850,
    allow_phone_calls: true,
    status: 'reserved',
    reserved_by_id: 'user6',
    reserved_by_name: 'Pedro',
    reserved_by_email: 'pedro@example.com',
    reserved_by_plate: '3456 RNL',
    created_date: new Date(Date.now() - 30 * 60000).toISOString()
  },
  {
    id: 'alert6',
    user_id: 'user6',
    user_name: 'Pedro',
    user_photo: mockUsers[5].photo,
    car_brand: 'Renault',
    car_model: 'Megane',
    car_color: 'blanco',
    car_plate: '3456 RNL',
    vehicle_type: 'car',
    address: 'Calle Goya, 50, Madrid',
    available_in_minutes: 15,
    price: 3.75,
    latitude: 40.4190,
    longitude: -3.6900,
    allow_phone_calls: true,
    status: 'completed',
    reserved_by_id: 'user7',
    reserved_by_name: 'Andrea',
    reserved_by_email: 'andrea@example.com',
    reserved_by_plate: '7890 SEAT',
    created_date: new Date(Date.now() - 120 * 60000).toISOString()
  },
  {
    id: 'alert7',
    user_id: 'user7',
    user_name: 'Andrea',
    user_photo: mockUsers[6].photo,
    car_brand: 'Seat',
    car_model: 'Ibiza',
    car_color: 'amarillo',
    car_plate: '7890 SEAT',
    vehicle_type: 'car',
    address: 'Retiro, Madrid',
    available_in_minutes: 45,
    price: 4.50,
    latitude: 40.4158,
    longitude: -3.6829,
    allow_phone_calls: true,
    status: 'active',
    created_date: new Date(Date.now() - 25 * 60000).toISOString()
  },
  {
    id: 'alert8',
    user_id: 'user8',
    user_name: 'Miguel',
    user_photo: mockUsers[7].photo,
    car_brand: 'Peugeot',
    car_model: '308',
    car_color: 'gris',
    car_plate: '2468 PEU',
    vehicle_type: 'suv',
    address: 'Bulevar Príncipe de Vergara, 80, Madrid',
    available_in_minutes: 30,
    price: 3.25,
    latitude: 40.4200,
    longitude: -3.6750,
    allow_phone_calls: true,
    status: 'active',
    created_date: new Date(Date.now() - 10 * 60000).toISOString()
  }
];

export const mockNotifications = [
  {
    id: 'notif1',
    type: 'reservation_request',
    recipient_id: 'user1',
    recipient_email: 'sofia@example.com',
    sender_id: 'user2',
    sender_name: 'Carlos Martínez',
    sender_photo: mockUsers[1].photo,
    alert_id: 'alert1',
    amount: 3.50,
    status: 'pending',
    read: false,
    created_date: new Date(Date.now() - 2 * 60000).toISOString()
  },
  {
    id: 'notif2',
    type: 'reservation_accepted',
    recipient_id: 'user3',
    recipient_email: 'maria@example.com',
    sender_id: 'user4',
    sender_name: 'Juan Rodríguez',
    sender_photo: mockUsers[3].photo,
    alert_id: 'alert3',
    amount: 5.00,
    status: 'completed',
    read: true,
    created_date: new Date(Date.now() - 60 * 60000).toISOString()
  },
  {
    id: 'notif3',
    type: 'payment_completed',
    recipient_id: 'user5',
    recipient_email: 'laura@example.com',
    sender_id: 'user6',
    sender_name: 'Pedro Fernández',
    sender_photo: mockUsers[5].photo,
    alert_id: 'alert5',
    amount: 3.00,
    status: 'completed',
    read: true,
    created_date: new Date(Date.now() - 90 * 60000).toISOString()
  },
  {
    id: 'notif4',
    type: 'buyer_nearby',
    recipient_id: 'user2',
    recipient_email: 'carlos@example.com',
    sender_id: 'user8',
    sender_name: 'Miguel Ángel López',
    sender_photo: mockUsers[7].photo,
    alert_id: 'alert2',
    amount: 4.00,
    status: 'completed',
    read: false,
    created_date: new Date(Date.now() - 30 * 60000).toISOString()
  }
];

export const mockTransactions = [
  {
    id: 'tx1',
    alert_id: 'alert6',
    seller_id: 'user6',
    seller_name: 'Pedro',
    buyer_id: 'user7',
    buyer_name: 'Andrea',
    amount: 3.75,
    seller_earnings: 3.00,
    platform_fee: 0.75,
    status: 'completed',
    address: 'Calle Goya, 50, Madrid',
    created_date: new Date(Date.now() - 150 * 60000).toISOString()
  },
  {
    id: 'tx2',
    alert_id: 'alert5',
    seller_id: 'user5',
    seller_name: 'Laura',
    buyer_id: 'user6',
    buyer_name: 'Pedro',
    amount: 3.00,
    seller_earnings: 2.40,
    platform_fee: 0.60,
    status: 'completed',
    address: 'Calle Ortega y Gasset, 10, Madrid',
    created_date: new Date(Date.now() - 100 * 60000).toISOString()
  },
  {
    id: 'tx3',
    alert_id: 'alert3',
    seller_id: 'user3',
    seller_name: 'María',
    buyer_id: 'user4',
    buyer_name: 'Juan',
    amount: 5.00,
    seller_earnings: 4.00,
    platform_fee: 1.00,
    status: 'completed',
    address: 'Gran Vía, 28, Madrid',
    created_date: new Date(Date.now() - 70 * 60000).toISOString()
  }
];

export const mockRatings = [
  {
    id: 'rating1',
    alert_id: 'alert6',
    rater_id: 'user7',
    rater_email: 'andrea@example.com',
    rated_id: 'user6',
    rated_email: 'pedro@example.com',
    rating: 5,
    comment: 'Muy bueno, puntal y confiable',
    role: 'seller',
    created_date: new Date(Date.now() - 140 * 60000).toISOString()
  },
  {
    id: 'rating2',
    alert_id: 'alert3',
    rater_id: 'user4',
    rater_email: 'juan@example.com',
    rated_id: 'user3',
    rated_email: 'maria@example.com',
    rating: 4,
    comment: 'Buena experiencia',
    role: 'seller',
    created_date: new Date(Date.now() - 60 * 60000).toISOString()
  },
  {
    id: 'rating3',
    alert_id: 'alert5',
    rater_id: 'user6',
    rater_email: 'pedro@example.com',
    rated_id: 'user5',
    rated_email: 'laura@example.com',
    rating: 5,
    comment: 'Excelente servicio',
    role: 'buyer',
    created_date: new Date(Date.now() - 95 * 60000).toISOString()
  }
];

export const mockConversations = [
  {
    id: 'conv1',
    participant1_id: 'user1',
    participant1_name: 'Sofia',
    participant1_photo: mockUsers[0].photo,
    participant2_id: 'user2',
    participant2_name: 'Carlos',
    participant2_photo: mockUsers[1].photo,
    alert_id: 'alert1',
    last_message_text: 'Vale, te espero aquí',
    last_message_at: new Date(Date.now() - 3 * 60000).toISOString(),
    unread_count_p1: 0,
    unread_count_p2: 2
  },
  {
    id: 'conv2',
    participant1_id: 'user5',
    participant1_name: 'Laura',
    participant1_photo: mockUsers[4].photo,
    participant2_id: 'user6',
    participant2_name: 'Pedro',
    participant2_photo: mockUsers[5].photo,
    alert_id: 'alert5',
    last_message_text: 'Muchas gracias por todo',
    last_message_at: new Date(Date.now() - 120 * 60000).toISOString(),
    unread_count_p1: 0,
    unread_count_p2: 0
  }
];

export const mockChatMessages = [
  {
    id: 'msg1',
    conversation_id: 'conv1',
    alert_id: 'alert1',
    sender_id: 'user2',
    sender_name: 'Carlos',
    sender_photo: mockUsers[1].photo,
    receiver_id: 'user1',
    message: '¿Todavía estás aparcado en Alcalá?',
    read: false,
    message_type: 'user',
    created_date: new Date(Date.now() - 5 * 60000).toISOString()
  },
  {
    id: 'msg2',
    conversation_id: 'conv1',
    alert_id: 'alert1',
    sender_id: 'user2',
    sender_name: 'Carlos',
    sender_photo: mockUsers[1].photo,
    receiver_id: 'user1',
    message: 'Estoy a 5 minutos',
    read: false,
    message_type: 'user',
    created_date: new Date(Date.now() - 4 * 60000).toISOString()
  },
  {
    id: 'msg3',
    conversation_id: 'conv1',
    alert_id: 'alert1',
    sender_id: 'user1',
    sender_name: 'Sofia',
    sender_photo: mockUsers[0].photo,
    receiver_id: 'user2',
    message: 'Vale, te espero aquí',
    read: true,
    message_type: 'user',
    created_date: new Date(Date.now() - 3 * 60000).toISOString()
  }
];